### ISSUE TITLE
Invalid client error when authorize

### ISSUE THREAD

**Issue by chris41188** [tokenly/tokenpass-client#1]
When trying to test out the example code I receive the following error when trying to authorizes (after pressing login/register now)

{
error: "invalid_client",
error_description: "Client authentication failed."
}

I believe I set my client id and secret correctly in the config file, 

here is the request 
https://tokenpass.tokenly.com/oauth/authorize?client_id=IBBTGRMgxbSi4eRio1VRpCPgzigOWZNa&redirect_uri=accesscontroltest.herokuapp.com&scope=user%2Ctca&state=947de368c4abb4e8612f21c91f4037fdd831f208&response_type=code

**Comment by deweller** [comment]
Make sure to add your Callback Endpoint for your application.  And it it should match the `redirect_uri` parameter that you pass exactly, including the scheme.

Here is an example:

![tokenpass](https://cloud.githubusercontent.com/assets/51414/14935865/b00021fa-0ea6-11e6-9623-db79200f828c.png)

**Comment by chris41188** [comment]
I forgot the http, apologies
